name: Sync Submodule Changes

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Branch to checkout in the reusable workflow"
        required: true

jobs:
  sync-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout parent repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update submodules
      run: git submodule update --remote --recursive

    - name: Detect changes
      id: detect_changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "changes=true" >> $GITHUB_ENV
        else
          echo "changes=false" >> $GITHUB_ENV
        fi

    - name: Show input value
      run: |
        echo Hello ${{ github.event.inputs.branch-name }}

    # - name: Commit and push changes to new repository
    #   if: env.changes == 'true'
    #   run: |
    #     git config --global user.name "github-actions[bot]"
    #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #     git add .
    #     git commit -m "Update submodules" || echo "No changes to commit"
    #     git remote set-url origin https://x-access-token:${{ secrets.TEST_GITHUB_TOKEN }}@github.com/lephat08/aem0merge-repo.git
    #     git branch -M main
    #     git push -u origin main
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
